### ISSUE TITLE
How to use normalization with CLI?

### ISSUE THREAD

**Issue by rbatorsky** [mad-lab/transit#15]
Hello,

I'm trying to run HMM method with normalization across many samples and sum over replicates, but I am getting a warning message that the normalization "Sum" is not expected.

This is an example of how I am running it:
```
python transit export combined_wig 1.wig,2.wig ref_updated.prot_table 1_2.combined.ttr.wig -n TTR

python transit hmm 1_2.combined.ttr.wig \
-r Sum \
ref_updated.prot_table \
1_2.combined.ttr.out \
-l
```

This is the output and warning that is generated:
```
[hmm] Starting HMM Method
[hmm] Getting Data
[hmm] Normalizing using: Sum
/opt/shared/python/2.7.6/lib/python2.7/site-packages/pytransit/norm_tools.py:594: UserWarning: Normalization method 'Sum' is unknown. Read-counts were not normalized.
  warnings.warn(warnstr)
[hmm] Performing LOESS Correction
[hmm] Running HMM Method... 100.0%   
[hmm] Finished HMM - Sites Method
[hmm] Adding File: 1_2.combined.ttr.out
[hmm] Creating HMM Genes Level Output
[hmm] Adding File: 1_2.combined.ttr_genes.out
[hmm] Finished HMM Method
```
Is my process correct, i.e. normalize and combine wig files, then run the HMM method with summing over replicates? If so, can the warning be safely ignored?

Thanks for your help.
Best,
Rebecca

**Comment by rbatorsky-claritas** [comment]
Hi again,

Looking closer at the results, there is a big difference between running HMM after normalizing the individual files vs. running on the normalized combined file. Does the HMM method accept combined wig files?

If not, I'm guessing my workflow should be this:
```
python transit normalize 1_wig 1.ttr.wig
python transit normalize 2_wig 2.ttr.wig

python transit hmm 1.ttr.wig,2.ttr.wig \
-r Sum \
ref_updated.prot_table \
1_2.ttr.out \
-l
```

For a couple of sites, I took a look at the different HMM results with individual normalization and combined normalization:
```
individual normed files 
1.ttrwig :
4030940 121
4030972 0
4030991 60
2.ttr.wig : 
4030940 11791
4030972 0
4030991 8167

result 1_2.ttr.out file with individual norm:
4030940	98368	0.00e+00 	0.00e+00 	3.54e-100	1.00e+00 	ES	
4030972	0	2.42e-61 	3.90e-63 	8.33e-67 	1.00e+00 	ES	
4030991	68075	0.00e+00 	0.00e+00 	1.52e-106	1.00e+00 	ES

combined norm file 1_2.combined.ttr.wig:
4030940	121.2	11791.7	ACX60_18990 (-)
4030972	0.0	0.0	ACX60_18990 (-)
4030991	60.6	8167.5	ACX60_18990 (-)

result 1_2.combined.ttr.out for combined norm:
4030940	299	0.00e+00 	1.00e+00 	6.49e-26 	1.44e-28 	GD	
4030972	0	1.94e-69 	1.00e+00 	1.99e-32 	3.87e-35 	GD	
4030991	149	0.00e+00 	1.00e+00 	3.50e-29 	7.28e-32 	GD
```
I think the second column in the out file from hmm should be the summed read counts, but it's not the sum in either case.
Thank you for any advice.
Best,
Rebecca

**Comment by rbatorsky-claritas** [comment]
Hello,
Thanks for looking at this.
Was this pull request in response to this issue?
I'd be very grateful for clarification on the workflow for normalization on the CLI.
Thanks,
Rebecca

**Comment by subsid** [comment]
Thanks for the report @rbatorsky-claritas.

Yes, your usage is correct. There was a bug with regard to "-r" flag in hmm. This has been fixed in release 2.3.3.

**Comment by rbatorsky-claritas** [comment]
Hello,
Thank you very much for looking into this.
The warning "Normalization method 'Sum'" has disappeared, but the results still do not appear to be correct with the CLI.

Here are two example sites (same as above), this time comparing 2.3.3 GUI with 2.3.3 CLI:
```
normalized sample 1:
4030940 121
4030972 0
4030991 60

normalized sample 2:
4030940 11791
4030972 0
4030991 8167

result gui:
4030940	11913	0.00e+00 	0.00e+00 	1.69e-21 	1.00e+00 	GA	
4030972	0	3.72e-62 	5.29e-64 	4.11e-15 	1.00e+00 	GA	
4030991	8228	0.00e+00 	0.00e+00 	1.60e-19 	1.00e+00 	GA

result cli:
4030940	98462	0.00e+00 	0.00e+00 	3.44e-100	1.00e+00 	ES	
4030972	0	2.37e-61 	3.82e-63 	8.16e-67 	1.00e+00 	ES	
4030991	68140	0.00e+00 	0.00e+00 	1.48e-106	1.00e+00 	ES	
```
The GUI appears to give a second column result that is the Sum, but CLI gives a much larger number.

I am running the GUI by choosing Analysis->HMM, then adding an annotation file, 2 "control" datasets, selecting Normalization=TTR and Replicates=Sum and selecting "Correct for Genome Positional Bias".

I am running the CLI with this code:
```
transit normalize 1_wig 1.ttr.wig
transit normalize 2_wig 2.ttr.wig

transit hmm 1.ttr.wig,2.ttr.wig \
-r Sum \
ref_updated.prot_table \
1_2.ttr.out \
-l
```

I appreciate your advice about the best way to run the CLI to get the same results as the GUI.
Best,
Rebecca

**Comment by subsid** [comment]
Ah, there was another bug in the GUI. The flag for LOESS correction (positional bias) was not being passed correctly, from the GUI. So the output produced by the CLI command is what you should expect. I have added a fix for this and pushed to master. 

We will include this fix in the next release. Can you clone this repo, and run transit from here? `python src/transit.py` will open transit is GUI. You can use `python src/transit.py hmm ...` for CLI mode.

P.S The normalization can be done using the `-n` flag for hmm. (Default is TTR) That should work now.

**Comment by subsid** [comment]
Yes, the 2.3.3 version from CLI should work correctly. Just to clarify, if you want to use the GUI (and run hmm with LOESS correction), you'll need to clone this repository and run transit GUI as `python src/transit.py`. (Until we release this fix in the PyPi package)

Sure. LOESS correction basically handles differences in coverage across the genome. You can see a coverage plot by clicking "Preview LOESS fit" in the GUI.
